server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.1.229:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - waf
    labels:
      job: varlogs
      __path__: /var/log/waf/**/*log
